# Generated by Django 3.0.3 on 2020-03-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200308_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(related_name='blog_topic', to='blog.Topic'),
        ),
    ]
