# Generated by Django 3.0.3 on 2020-04-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, help_text="Post's banner image", null=True, upload_to=''),
        ),
    ]
