# Generated by Django 3.0.3 on 2020-04-13 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='image',
        ),
    ]
